# This is a basic workflow to help you get started with Actions

name: STREAMLINK LIVE

# Controls when the action will run. 
on:
  schedule:
    - cron: "*/40 * * * *"
 
  push:
    branches:
    - master
    - main

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # 
      - name: config
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

         
      - name: Instalando requests
        run: |
         pip install youtube-dl 
         pip install requests 
         pip install beautifulsoup4 
         pip install fastapi 
         pip install uvicorn 
         pip install schedule
         pip install selenium
         
      - name: execute py script
        run: python lista5str5.py         

              
      - name: execute py script
        run: python lista5str5.py 
         touch ./lista2str.ts
         sudo cat >./lista2str.ts <<EOL
         
         #EXTM3U
         #EXT-X-VERSION:3
         #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
         #EXTINF:-1 tvg-id="$(yt-dlp --get-title https://www.youtube.com/watch?v=EeQnkxY9QFs)" group-title="Reality Show'S Live" group-title="CNN's" tvg-logo="$(yt-dlp --get-thumbnail https://www.youtube.com/watch?v=EeQnkxY9QFs)", YOUTUBEAOVIVO - $(yt-dlp --get-title https://www.youtube.com/watch?v=EeQnkxY9QFs)
         $(streamlink  --hls-duration 00:02:00 --output "BBUSAMEXICO.ts"  https://www.youtube.com/@TelemundoEntretenimiento/live best)
         
         #EXTM3U
         #EXT-X-VERSION:3
         #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
         #EXTINF:-1 tvg-id="cnnpthd.tv.vodafone.pt" tvg-logo="https://raw.githubusercontent.com/LITUATUI/M3UPT/main/logos/CNN-Portugal.png",CNN Portugal
         $(streamlink  --hls-duration 00:02:00 --output "CNNPORTUGAL.mp4" https://tviplayer.iol.pt/direto/CNN best)
         #EXTM3U
         #EXT-X-VERSION:3
         #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
         #EXTINF:-1 tvg-id="tvihd.tv.vodafone.pt" tvg-logo="https://raw.githubusercontent.com/LITUATUI/M3UPT/main/logos/TVI.png",TVI
         $(streamlink --hls-segment-stream-data --hls-live-edge 5 --hls-segment-threads 10 --ffmpeg-ffmpeg /usr/local/bin/ffmpeg --hls-live-edge 6 --hls-duration 00:02:00 --output "TVI.ts"  https://tviplayer.iol.pt/direto/TVI best)
         #EXTM3U
         #EXT-X-VERSION:3
         #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
         #EXTINF:-1 tvg-id="TVIFIC.meo.pt" tvg-logo="https://raw.githubusercontent.com/LITUATUI/M3UPT/main/logos/TVI-Ficção.png",TVI Ficção
         $(streamlink --url --default-stream  --hls-duration 00:02:00 --output "TVI FICÇÃO.ts"  https://tviplayer.iol.pt/direto/TVI_FICCAO best)
         #EXTM3U
         #EXT-X-VERSION:3
         #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
         #EXTINF:-1,
         $(streamlink --url --default-stream  --hls-duration 00:02:00 --output "TVI AFRICA.ts"  https://tviplayer.iol.pt/direto/TVI_AFRICA best)
         #EXTM3U
         #EXT-X-VERSION:3
         #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
         #EXTINF:-1 tvg-id="TVIInt.pt" tvg-logo="https://github.com/LITUATUI/M3UPT/raw/main/logos/TVI-Internacional.png",TVI Internacional
         $(streamlink --url --default-stream  --hls-duration 00:02:00 --output "TVI INTERNACIONAL.ts"  https://tviplayer.iol.pt/direto/TVI_INTERNACIONAL best)
         EOL
         

      - name: git add
        run: |
          git add -A
          ls -la 
          
      - name: commit & push
        run: |
          git commit -m "links atualizados"
          git push
