# This is a basic workflow to help you get started with Actions

name: STREAMLINK LIVE

# Controls when the action will run. 
on:
  schedule:
    - cron: "*/40 * * * *"
 
  push:
    branches:
    - master
    - main

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # 
      - name: config
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

         
      - name: Instalando requests
        run: |
         pip install youtube-dl 
         pip install requests 
         pip install beautifulsoup4 
         pip install fastapi 
         pip install uvicorn 
         pip install schedule
         pip install selenium
         
      - name: execute py script
        run: python lista5str5.py         

              

       
         

      - name: git add
        run: |
          git add -A
          ls -la 
          
      - name: commit & push
        run: |
          git commit -m "links atualizados"
          git push
