# This is a basic workflow to help you get started with Actions

name: STREAMLINK LIVE

# Controls when the action will run. 
on:
  schedule:
    - cron: "*/40 * * * *"
 
  push:
    branches:
    - master
    - main

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # 
      - name: config
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
      - name: Instalando yt-dlp 
        run: |
         sudo wget https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -O /usr/local/bin/yt-dlp
         sudo chmod a+rx /usr/local/bin/yt-dlp
      - name: Instalando youtube-dl 
        run: |
         sudo wget https://yt-dl.org/downloads/latest/youtube-dl -O /usr/local/bin/youtube-dl
         sudo chmod a+rx /usr/local/bin/youtube-dl    
         youtube-dl -U
      - name: Instalando streamlink
        run: |
         pip install --user --upgrade streamlink   
         
      - name: Instalando requests
        run: |
         pip install youtube-dl 
         pip install requests 
         pip install beautifulsoup4 
         pip install fastapi 
         pip install uvicorn 
         pip install schedule
         pip install selenium
         
        
         # Get the current date and time in the São Paulo timezone
         now = datetime.datetime.now(tz)
         tempo = now.strftime('%m%d_%H%M%S')
         tempo2 = now.strftime('-%Y')
         filename = "BB" + tempo + tempo2 + ".ts"
              
      - name: Get ${filename}
        run: |
         touch ./${filename}
         sudo cat >./${filename} <<EOL
         


         $(streamlink --force --hls-duration 00:00:15 --output "${filename}" https://www.youtube.com/@TelemundoEntretenimiento/live best)


         EOL 
   
      - name: git add
        run: |
          git add -A
          ls -la 
          
      - name: commit & push
        run: |
          git commit -m "links atualizados"
          git push
