# This is a basic workflow to help you get started with Actions

name: M3U generator

# Controls when the action will run. 
on:
  schedule:
    - cron: "*/41 * * * *"
    
  pull_request:
    branches:
      - main
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      #- name: Run a one-line script
      #  run: echo testing!

      # Runs a set of commands using the runners shell 
      - name: config
        run: |
          git config --global user.email "vijayelectro2002@gmail.com"
          git config --global user.name "vijay6672"
      
      
      # Installing streamlink
      - name: Install streamlink
        run: |
          pip install --user --upgrade streamlink   
          
      # Installing dependencies
      - name: Install dependencies
        run: |
          pip install youtube-dl 
          pip install requests 
          pip install beautifulsoup4 
          pip install fastapi 
          pip install uvicorn 
          pip install schedule
          pip install selenium
          pip install datetime
          pip install pytz
      
      - name: Get BBMEXICOUSA.ts
        run: |
         touch ./BBMEXICOUSA.ts
         sudo cat >./BBMEXICOUSA.ts <<EOL
     
         $(streamlink --force --hls-duration 00:00:15 --output "BBMEXICOUSA.ts" https://www.youtube.com/@TelemundoEntretenimiento/live best)
         $(streamlink --force --hls-duration 00:00:15 --output "CBSNEWS.ts" https://www.cbsnews.com/live/ best)
         $(streamlink --force --hls-duration 00:00:15 --output "CNNPORTUGAL.ts" https://tviplayer.iol.pt/direto/CNN best best)
         


      - name: Get BBMEXICOUSA.ts
        run: |
         touch ./BBMEXICOUSA.ts
         sudo cat >./BBMEXICOUSA.ts <<EOL
     
         $(streamlink --force --hls-duration 00:00:15 --output "GRAVADOS/$(date +%d%m)_$(date +%H%M%S)_BBMEXICOUSA_-$(date +%Y).ts" https://www.youtube.com/@TelemundoEntretenimiento/live best)
         $(streamlink --force --hls-duration 00:00:15 --output "GRAVADOS/$(date +%d%m)_$(date +%H%M%S)_CBSNEWS_-$(date +%Y).ts" https://www.cbsnews.com/live/ best)
         $(streamlink --force --hls-duration 00:00:15 --output "GRAVADOS/CNNPORTUGAL.ts" https://tviplayer.iol.pt/direto/CNN best best)         
        
      - name: git add
        run: |
          git add -A
          ls -la 
          
      - name: commit & push
        run: |
          git commit -m "links are updated"
          git push
          
